<a href="https://colab.research.google.com/github/DmitryiLaptev/NumericalMethods_HW/blob/main/5_%D0%A1%D0%9B%D0%90%D0%A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import math

In [30]:
for n in (4, 8, 16, 32, 64):
  sum = 0
  A = np.arange(n*n, dtype=float).reshape(n, n)
  for i in range (0, n):
    for j in range (0, n):
      A[i][j] = 1 / (i + 1 + j + 1 - 1)
  B = np.arange(n, dtype = float).reshape(n, 1)
  for j in range (0, n):
    for i in range (0, n):
      sum = sum + A[i][j]
    B[j][0] = sum
    sum = 0
  Btransp = np.arange(n, dtype = float)
  for i in range (0, n):
    Btransp[i] = B[i][0]

  def gauss_metod(a,b):
      n = len(b)
     # Elimination phase
      for k in range(0,n-1):
          for i in range(k+1,n):
              if a[i,k] != 0.0:
                  #if not null define λ
                  lam = a [i,k]/a[k,k]
                  #we calculate the new row of the matrix
                  a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                  #we update vector b
                  b[i] = b[i] - lam*b[k]
                  # backward substitution
      for k in range(n-1,-1,-1):
          b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]

      return b

  aOrig = A.copy() # save original matrix A
  bOrig = B.copy() #save original vector b
  X = gauss_metod(aOrig, bOrig)
  #print A transformed for check
  print('n =', n)
  print('Метод Гаусса:')
  print("X =\n",X)
  #print("\nCheck result: [a]{x} - b =\n",np.dot(A,x) - B)
  R = B - np.matmul(A,X)
  print("R =\n",R)

  def zeidel_metod(A, b, eps):
      n = len(A)
      x = np.zeros(n)  # zero vector

      converge = False
      while not converge:
          x_new = np.copy(x)
          for i in range(n):
              s1 = math.fsum(A[i][j] * x_new[j] for j in range(i))
              s2 = math.fsum(A[i][j] * x[j] for j in range(i + 1, n))
              x_new[i] = (b[i] - s1 - s2) / A[i][i]

          converge = np.sqrt(math.fsum((x_new[i] - x[i]) ** 2 for i in range(n))) <= eps
          x = x_new

      return x
  X1 = zeidel_metod(A, Btransp, 1e-5)
  X1transp = np.ones((n, 1))
  for i in range (0, n):
    X1transp[i][0] = X1[i]
  print('Метод Зейделя:')
  print("X =\n",X1transp)
  #print("\nCheck result: [a]{x} - b =\n",np.dot(A,x) - B)
  R = B - np.matmul(A,X1transp)
  print("R =\n",R)

n = 4
Метод Гаусса:
X =
 [[1.]
 [1.]
 [1.]
 [1.]]
R =
 [[0.]
 [0.]
 [0.]
 [0.]]
Метод Зейделя:
X =
 [[1.00032369]
 [0.9965225 ]
 [1.00815675]
 [0.99478583]]
R =
 [[-3.14043957e-07]
 [ 9.67609977e-07]
 [-8.43956194e-07]
 [ 0.00000000e+00]]
n = 8
Метод Гаусса:
X =
 [[1.        ]
 [1.        ]
 [0.99999998]
 [1.00000013]
 [0.99999966]
 [1.00000049]
 [0.99999965]
 [1.0000001 ]]
R =
 [[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.22044605e-16]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.11022302e-16]
 [ 0.00000000e+00]]
Метод Зейделя:
X =
 [[0.99972543]
 [1.00198912]
 [1.00290655]
 [0.98119714]
 [1.00459802]
 [1.01847975]
 [1.00961483]
 [0.98110812]]
R =
 [[ 2.43988978e-07]
 [-8.81312411e-07]
 [ 7.85263595e-07]
 [ 4.16620429e-07]
 [-9.01174284e-08]
 [-3.05684771e-07]
 [-2.44514715e-07]
 [ 0.00000000e+00]]
n = 16
Метод Гаусса:
X =
 [[ 1.00000004e+00]
 [ 9.99992357e-01]
 [ 1.00035813e+00]
 [ 9.92915973e-01]
 [ 1.07461449e+00]
 [ 5.29206540e-01]
 [ 2.89611126e+00]
 [-4.01576456e+